// A small searchable emoji dataset for the Quick Keys icon picker.
//
// Self-contained on purpose: no dependency, no network, no lazy chunk. The
// picker needs "type a word, get the obvious emoji", not the full Unicode
// catalogue, so this is a hand-kept set of the ones people actually reach for
// plus the dev-adjacent favourites (rocket, bug, wrench, sparkles, ticks).
//
// The empty query keeps showing the curated grid from lib/quickKeys, so the
// picker looks exactly as it did before anyone types.
import { EMOJI_CHOICES } from "./quickKeys"

export interface EmojiEntry {
  char: string
  /** Lower-case display name; also the primary match target. */
  name: string
  /** Extra words that should find this emoji. */
  keywords: string[]
}

/** [char, name, ...keywords] — tuples keep the table readable at this size. */
const RAW: [string, string, ...string[]][] = [
  // ---- Smileys & emotion --------------------------------------------------
  ["😀", "grinning face", "smile", "happy", "grin"],
  ["😃", "grinning face with big eyes", "smile", "happy"],
  ["😄", "grinning face with smiling eyes", "smile", "happy", "joy"],
  ["😁", "beaming face", "smile", "grin", "happy"],
  ["😆", "grinning squinting face", "laugh", "haha", "happy"],
  ["😅", "grinning face with sweat", "laugh", "relief", "phew"],
  ["🤣", "rolling on the floor laughing", "rofl", "laugh", "lol"],
  ["😂", "face with tears of joy", "laugh", "lol", "cry", "funny"],
  ["🙂", "slightly smiling face", "smile", "ok"],
  ["🙃", "upside down face", "sarcasm", "irony", "silly"],
  ["😉", "winking face", "wink", "flirt"],
  ["😊", "smiling face with smiling eyes", "blush", "happy", "warm"],
  ["😇", "smiling face with halo", "angel", "innocent"],
  ["🥰", "smiling face with hearts", "love", "adore"],
  ["😍", "heart eyes", "love", "crush", "adore"],
  ["😘", "face blowing a kiss", "kiss", "love"],
  ["😗", "kissing face", "kiss"],
  ["😙", "kissing face with smiling eyes", "kiss"],
  ["😋", "face savoring food", "yum", "tasty", "delicious"],
  ["😛", "face with tongue", "tongue", "cheeky"],
  ["😜", "winking face with tongue", "silly", "joke"],
  ["🤪", "zany face", "crazy", "wild", "goofy"],
  ["😝", "squinting face with tongue", "tongue", "silly"],
  ["🤑", "money mouth face", "money", "rich", "cash"],
  ["🤗", "hugging face", "hug", "welcome"],
  ["🤭", "face with hand over mouth", "oops", "giggle", "secret"],
  ["🤫", "shushing face", "quiet", "shh", "secret", "silence"],
  ["🤔", "thinking face", "think", "hmm", "consider", "question"],
  ["🤐", "zipper mouth face", "quiet", "secret", "silence"],
  ["🤨", "face with raised eyebrow", "skeptical", "suspicious", "doubt"],
  ["😐", "neutral face", "meh", "blank", "deadpan"],
  ["😑", "expressionless face", "blank", "meh"],
  ["😶", "face without mouth", "silent", "speechless", "blank"],
  ["😏", "smirking face", "smirk", "smug"],
  ["😒", "unamused face", "meh", "annoyed", "unimpressed"],
  ["🙄", "face with rolling eyes", "eyeroll", "annoyed", "whatever"],
  ["😬", "grimacing face", "awkward", "eek", "yikes"],
  ["🤥", "lying face", "lie", "pinocchio"],
  ["😌", "relieved face", "calm", "content", "phew"],
  ["😔", "pensive face", "sad", "down"],
  ["😪", "sleepy face", "tired", "sleep"],
  ["🤤", "drooling face", "drool", "want"],
  ["😴", "sleeping face", "sleep", "zzz", "tired"],
  ["😷", "face with medical mask", "sick", "mask", "ill"],
  ["🤒", "face with thermometer", "sick", "fever", "ill"],
  ["🤕", "face with head bandage", "hurt", "injured"],
  ["🤢", "nauseated face", "sick", "gross", "yuck"],
  ["🤮", "face vomiting", "sick", "vomit", "gross"],
  ["🤧", "sneezing face", "sneeze", "cold", "sick"],
  ["🥵", "hot face", "heat", "sweating", "burning"],
  ["🥶", "cold face", "freezing", "frozen", "ice"],
  ["🥴", "woozy face", "dizzy", "drunk", "confused"],
  ["😵", "dizzy face", "confused", "knocked out", "whoa"],
  ["🤯", "exploding head", "mind blown", "shock", "wow", "whoa"],
  ["🤠", "cowboy hat face", "cowboy", "yeehaw"],
  ["🥳", "partying face", "party", "celebrate", "birthday", "hooray"],
  ["😎", "smiling face with sunglasses", "cool", "sunglasses", "chill"],
  ["🤓", "nerd face", "nerd", "geek", "glasses", "smart"],
  ["🧐", "face with monocle", "inspect", "examine", "scrutiny"],
  ["😕", "confused face", "unsure", "puzzled"],
  ["😟", "worried face", "concern", "anxious"],
  ["🙁", "slightly frowning face", "sad", "frown"],
  ["😮", "face with open mouth", "surprise", "wow", "shock"],
  ["😯", "hushed face", "surprise", "quiet"],
  ["😲", "astonished face", "shock", "gasp", "wow"],
  ["😳", "flushed face", "embarrassed", "blush", "shock"],
  ["🥺", "pleading face", "please", "beg", "puppy eyes"],
  ["😦", "frowning face with open mouth", "sad", "shock"],
  ["😨", "fearful face", "scared", "fear"],
  ["😰", "anxious face with sweat", "nervous", "worried", "stress"],
  ["😥", "sad but relieved face", "sad", "phew"],
  ["😢", "crying face", "cry", "sad", "tear"],
  ["😭", "loudly crying face", "sob", "cry", "sad"],
  ["😱", "face screaming in fear", "scream", "shock", "horror"],
  ["😖", "confounded face", "frustrated", "ugh"],
  ["😣", "persevering face", "struggle", "effort"],
  ["😞", "disappointed face", "sad", "let down"],
  ["😓", "downcast face with sweat", "stress", "work", "tired"],
  ["😩", "weary face", "tired", "exhausted", "ugh"],
  ["😫", "tired face", "exhausted", "ugh", "done"],
  ["🥱", "yawning face", "tired", "bored", "sleepy"],
  ["😤", "face with steam from nose", "frustrated", "determined", "angry"],
  ["😡", "enraged face", "angry", "mad", "rage"],
  ["😠", "angry face", "mad", "annoyed"],
  ["🤬", "face with symbols on mouth", "swearing", "cursing", "angry"],
  ["😈", "smiling face with horns", "devil", "mischief", "evil"],
  ["💀", "skull", "dead", "death", "fatal", "crash"],
  ["☠️", "skull and crossbones", "danger", "poison", "death", "fatal"],
  ["💩", "pile of poo", "poop", "crap", "bad"],
  ["🤡", "clown face", "clown", "joke", "silly"],
  ["👻", "ghost", "spooky", "halloween", "boo"],
  ["👽", "alien", "ufo", "space", "extraterrestrial"],
  ["👾", "alien monster", "game", "arcade", "invader", "retro"],
  ["🤖", "robot", "bot", "ai", "android", "automation", "agent"],
  ["🎃", "jack o lantern", "halloween", "pumpkin"],
  ["😺", "grinning cat", "cat", "happy"],
  ["😻", "smiling cat with heart eyes", "cat", "love"],
  ["🙈", "see no evil monkey", "monkey", "hide", "oops"],
  ["🙉", "hear no evil monkey", "monkey", "ignore"],
  ["🙊", "speak no evil monkey", "monkey", "quiet", "secret"],

  // ---- Gestures & body ----------------------------------------------------
  ["👋", "waving hand", "wave", "hello", "hi", "bye", "greeting"],
  ["🤚", "raised back of hand", "hand", "stop"],
  ["🖐️", "hand with fingers splayed", "hand", "five"],
  ["✋", "raised hand", "stop", "hand", "high five"],
  ["🖖", "vulcan salute", "spock", "star trek"],
  ["👌", "ok hand", "ok", "perfect", "good", "fine"],
  ["🤌", "pinched fingers", "italian", "gesture"],
  ["🤏", "pinching hand", "small", "tiny", "little"],
  ["✌️", "victory hand", "peace", "two", "win"],
  ["🤞", "crossed fingers", "luck", "hope", "wish"],
  ["🤟", "love you gesture", "love", "rock"],
  ["🤘", "sign of the horns", "rock", "metal"],
  ["🤙", "call me hand", "shaka", "hang loose", "call"],
  ["👈", "backhand index pointing left", "left", "point", "previous"],
  ["👉", "backhand index pointing right", "right", "point", "next"],
  ["👆", "backhand index pointing up", "up", "point", "above"],
  ["👇", "backhand index pointing down", "down", "point", "below"],
  ["☝️", "index pointing up", "up", "one", "attention"],
  ["👍", "thumbs up", "yes", "approve", "good", "lgtm", "ok", "like"],
  ["👎", "thumbs down", "no", "reject", "bad", "dislike"],
  ["✊", "raised fist", "fist", "power", "solidarity"],
  ["👊", "oncoming fist", "punch", "bump", "fist"],
  ["👏", "clapping hands", "clap", "applause", "bravo", "well done"],
  ["🙌", "raising hands", "celebrate", "hooray", "praise", "yay"],
  ["👐", "open hands", "hug", "open"],
  ["🤲", "palms up together", "please", "offer", "pray"],
  ["🤝", "handshake", "deal", "agree", "partnership", "merge"],
  ["🙏", "folded hands", "thanks", "please", "pray", "gratitude"],
  ["✍️", "writing hand", "write", "sign", "author", "edit"],
  ["💪", "flexed biceps", "strong", "muscle", "power", "strength"],
  ["🦾", "mechanical arm", "robot", "prosthetic", "strong"],
  ["🧠", "brain", "smart", "think", "mind", "intelligence", "memory"],
  ["👀", "eyes", "look", "watch", "review", "see", "attention"],
  ["👁️", "eye", "look", "watch", "see"],
  ["👂", "ear", "listen", "hear"],
  ["👃", "nose", "smell"],
  ["🦷", "tooth", "teeth", "dentist"],
  ["🦴", "bone", "skeleton"],
  ["👅", "tongue", "taste"],
  ["👄", "mouth", "lips", "kiss"],

  // ---- People -------------------------------------------------------------
  ["👶", "baby", "infant", "child", "new"],
  ["🧒", "child", "kid"],
  ["🧑", "person", "adult", "human", "user"],
  ["👨", "man", "male", "guy"],
  ["👩", "woman", "female", "lady"],
  ["🧓", "older person", "elder", "senior"],
  ["👮", "police officer", "cop", "police", "law"],
  ["🕵️", "detective", "spy", "investigate", "search", "sleuth"],
  ["👷", "construction worker", "builder", "hardhat", "work"],
  ["🧑‍💻", "technologist", "developer", "programmer", "coder", "engineer"],
  ["👨‍💻", "man technologist", "developer", "programmer", "coder"],
  ["👩‍💻", "woman technologist", "developer", "programmer", "coder"],
  ["🧑‍🔬", "scientist", "research", "lab"],
  ["🧑‍🏫", "teacher", "instructor", "professor"],
  ["🧑‍⚕️", "health worker", "doctor", "nurse", "medical"],
  ["🧑‍🚀", "astronaut", "space", "nasa"],
  ["🧑‍🚒", "firefighter", "fire", "rescue"],
  ["🥷", "ninja", "stealth", "hidden"],
  ["🦸", "superhero", "hero", "super"],
  ["🦹", "supervillain", "villain", "evil"],
  ["🧙", "mage", "wizard", "magic", "sorcerer"],
  ["🧝", "elf", "fantasy"],
  ["🧟", "zombie", "undead", "walking dead"],
  ["👑", "crown", "king", "queen", "royal", "best", "winner"],
  ["🧑‍🍳", "cook", "chef", "kitchen"],
  ["🕺", "man dancing", "dance", "party"],
  ["💃", "woman dancing", "dance", "party"],
  ["🚶", "person walking", "walk", "pedestrian"],
  ["🏃", "person running", "run", "fast", "sprint", "race"],
  ["🧘", "person in lotus position", "meditate", "yoga", "calm", "zen"],

  // ---- Animals & nature ---------------------------------------------------
  ["🐶", "dog face", "puppy", "pet"],
  ["🐕", "dog", "puppy", "pet"],
  ["🐺", "wolf", "howl"],
  ["🦊", "fox", "firefox"],
  ["🐱", "cat face", "kitten", "pet"],
  ["🐈", "cat", "kitten", "pet"],
  ["🦁", "lion", "king", "brave"],
  ["🐯", "tiger face", "tiger"],
  ["🐮", "cow face", "cow"],
  ["🐷", "pig face", "pig"],
  ["🐸", "frog", "toad", "pepe"],
  ["🐵", "monkey face", "monkey"],
  ["🐒", "monkey", "ape"],
  ["🦍", "gorilla", "ape", "strong"],
  ["🐔", "chicken", "hen"],
  ["🐧", "penguin", "linux", "tux"],
  ["🐦", "bird", "tweet", "twitter"],
  ["🦅", "eagle", "hawk", "bird"],
  ["🦉", "owl", "wise", "night"],
  ["🦇", "bat", "night", "vampire"],
  ["🐝", "honeybee", "bee", "buzz", "busy"],
  ["🐛", "bug", "caterpillar", "issue", "defect", "error", "insect"],
  ["🦋", "butterfly", "transform", "change"],
  ["🐌", "snail", "slow", "sluggish", "performance"],
  ["🐜", "ant", "insect", "small"],
  ["🕷️", "spider", "web", "crawler", "scraper"],
  ["🕸️", "spider web", "web", "crawl", "trap", "network"],
  ["🦂", "scorpion", "sting", "danger"],
  ["🐢", "turtle", "slow", "tortoise", "performance"],
  ["🐍", "snake", "python", "serpent"],
  ["🦎", "lizard", "gecko", "reptile"],
  ["🐙", "octopus", "tentacles", "kraken"],
  ["🦑", "squid", "ink"],
  ["🦀", "crab", "rust", "crustacean"],
  ["🐟", "fish", "swim"],
  ["🐠", "tropical fish", "fish", "reef"],
  ["🐬", "dolphin", "sea", "smart"],
  ["🐳", "spouting whale", "whale", "docker", "ocean"],
  ["🐋", "whale", "ocean", "big"],
  ["🦈", "shark", "danger", "ocean"],
  ["🐊", "crocodile", "alligator", "danger"],
  ["🐘", "elephant", "memory", "big", "postgres"],
  ["🦏", "rhinoceros", "rhino"],
  ["🐴", "horse face", "horse"],
  ["🦄", "unicorn", "magic", "rare", "startup", "special"],
  ["🐄", "cow", "cattle"],
  ["🐖", "pig", "hog"],
  ["🐑", "ewe", "sheep", "flock"],
  ["🐿️", "chipmunk", "squirrel"],
  ["🦔", "hedgehog", "spiky"],
  ["🌵", "cactus", "desert", "dry", "plant"],
  ["🌲", "evergreen tree", "tree", "pine", "forest"],
  ["🌳", "deciduous tree", "tree", "forest"],
  ["🌴", "palm tree", "beach", "vacation", "tropical"],
  ["🌱", "seedling", "sprout", "grow", "new", "plant", "start"],
  ["🌿", "herb", "plant", "leaf", "green"],
  ["☘️", "shamrock", "clover", "luck", "irish"],
  ["🍀", "four leaf clover", "luck", "lucky", "fortune"],
  ["🍁", "maple leaf", "autumn", "fall", "canada"],
  ["🍂", "fallen leaf", "autumn", "fall"],
  ["🍃", "leaf fluttering in wind", "leaf", "wind", "nature"],
  ["🌷", "tulip", "flower", "spring"],
  ["🌹", "rose", "flower", "love"],
  ["🌺", "hibiscus", "flower", "tropical"],
  ["🌸", "cherry blossom", "flower", "sakura", "spring"],
  ["🌼", "blossom", "flower", "daisy"],
  ["🌻", "sunflower", "flower", "sun"],
  ["🍄", "mushroom", "fungus", "toadstool"],
  ["🌍", "globe showing europe africa", "earth", "world", "global", "planet"],
  ["🌎", "globe showing americas", "earth", "world", "global", "planet"],
  ["🌏", "globe showing asia australia", "earth", "world", "global", "planet"],
  ["🌐", "globe with meridians", "internet", "web", "world", "network", "i18n"],
  ["🌙", "crescent moon", "moon", "night", "dark mode", "sleep"],
  ["⭐", "star", "favorite", "rating", "starred"],
  ["🌟", "glowing star", "star", "shine", "special"],
  ["💫", "dizzy", "star", "sparkle"],
  ["☀️", "sun", "sunny", "light mode", "day", "bright"],
  ["🌤️", "sun behind small cloud", "weather", "partly cloudy"],
  ["☁️", "cloud", "cloudy", "weather", "server", "hosting"],
  ["🌧️", "cloud with rain", "rain", "weather", "storm"],
  ["⛈️", "cloud with lightning and rain", "storm", "thunder", "weather"],
  ["🌈", "rainbow", "colors", "pride", "spectrum"],
  ["❄️", "snowflake", "snow", "cold", "freeze", "winter"],
  ["🧊", "ice", "ice cube", "cold", "frozen", "freeze", "chill"],
  ["🔥", "fire", "flame", "hot", "burn", "lit", "trending", "urgent"],
  ["💧", "droplet", "water", "drop", "liquid"],
  ["🌊", "water wave", "wave", "ocean", "sea", "surf", "flood"],
  ["⚡", "high voltage", "lightning", "fast", "power", "energy", "zap", "electric"],
  ["💥", "collision", "boom", "explosion", "crash", "impact", "bang"],
  ["🌪️", "tornado", "storm", "chaos", "whirlwind"],

  // ---- Food & drink -------------------------------------------------------
  ["🍏", "green apple", "apple", "fruit"],
  ["🍎", "red apple", "apple", "fruit"],
  ["🍐", "pear", "fruit"],
  ["🍊", "tangerine", "orange", "fruit"],
  ["🍋", "lemon", "citrus", "sour", "fruit"],
  ["🍌", "banana", "fruit"],
  ["🍉", "watermelon", "fruit", "summer"],
  ["🍇", "grapes", "fruit", "wine"],
  ["🍓", "strawberry", "fruit", "berry"],
  ["🫐", "blueberries", "berry", "fruit"],
  ["🍒", "cherries", "fruit", "cherry"],
  ["🍑", "peach", "fruit"],
  ["🥭", "mango", "fruit", "tropical"],
  ["🍍", "pineapple", "fruit", "tropical"],
  ["🥥", "coconut", "tropical"],
  ["🥝", "kiwi fruit", "fruit"],
  ["🍅", "tomato", "vegetable"],
  ["🥑", "avocado", "toast", "guacamole"],
  ["🥦", "broccoli", "vegetable", "green"],
  ["🥕", "carrot", "vegetable"],
  ["🌽", "ear of corn", "corn", "maize"],
  ["🌶️", "hot pepper", "spicy", "chili", "hot"],
  ["🥔", "potato", "vegetable"],
  ["🍞", "bread", "loaf", "bakery"],
  ["🥐", "croissant", "pastry", "french"],
  ["🥖", "baguette", "bread", "french"],
  ["🧀", "cheese wedge", "cheese"],
  ["🥚", "egg", "breakfast"],
  ["🍳", "cooking", "fried egg", "breakfast", "pan"],
  ["🥞", "pancakes", "breakfast", "stack"],
  ["🥓", "bacon", "breakfast", "meat"],
  ["🍔", "hamburger", "burger", "fast food"],
  ["🍟", "french fries", "fries", "fast food"],
  ["🍕", "pizza", "slice", "italian"],
  ["🌭", "hot dog", "sausage"],
  ["🌮", "taco", "mexican"],
  ["🌯", "burrito", "wrap", "mexican"],
  ["🥗", "green salad", "salad", "healthy"],
  ["🍝", "spaghetti", "pasta", "italian", "noodles"],
  ["🍜", "steaming bowl", "ramen", "noodles", "soup"],
  ["🍣", "sushi", "japanese", "fish"],
  ["🍱", "bento box", "japanese", "lunch"],
  ["🍚", "cooked rice", "rice", "bowl"],
  ["🍩", "doughnut", "donut", "sweet"],
  ["🍪", "cookie", "biscuit", "sweet", "browser"],
  ["🎂", "birthday cake", "cake", "birthday", "celebrate", "anniversary"],
  ["🍰", "shortcake", "cake", "slice", "dessert"],
  ["🧁", "cupcake", "sweet", "dessert"],
  ["🍫", "chocolate bar", "chocolate", "sweet"],
  ["🍬", "candy", "sweet"],
  ["🍭", "lollipop", "candy", "sweet"],
  ["🍿", "popcorn", "movie", "watching", "snack"],
  ["🧂", "salt", "seasoning"],
  ["☕", "hot beverage", "coffee", "tea", "cafe", "morning", "caffeine"],
  ["🍵", "teacup without handle", "tea", "green tea", "calm"],
  ["🧃", "beverage box", "juice", "drink"],
  ["🥤", "cup with straw", "soda", "drink", "soft drink"],
  ["🍺", "beer mug", "beer", "drink", "pub", "celebrate"],
  ["🍻", "clinking beer mugs", "cheers", "beer", "celebrate"],
  ["🥂", "clinking glasses", "cheers", "champagne", "celebrate", "toast"],
  ["🍷", "wine glass", "wine", "drink"],
  ["🥃", "tumbler glass", "whisky", "whiskey", "drink"],
  ["🍾", "bottle with popping cork", "champagne", "celebrate", "launch", "release"],

  // ---- Activities & objects ----------------------------------------------
  ["⚽", "soccer ball", "football", "sport"],
  ["🏀", "basketball", "sport", "hoop"],
  ["🏈", "american football", "sport", "nfl"],
  ["⚾", "baseball", "sport"],
  ["🎾", "tennis", "sport", "racquet"],
  ["🏐", "volleyball", "sport"],
  ["🏉", "rugby football", "sport"],
  ["🎱", "pool 8 ball", "billiards", "eight ball"],
  ["🏓", "ping pong", "table tennis", "sport"],
  ["🏸", "badminton", "sport"],
  ["🥅", "goal net", "goal", "sport", "target"],
  ["⛳", "flag in hole", "golf", "hole", "goal"],
  ["🏹", "bow and arrow", "archery", "target", "aim", "sagittarius"],
  ["🎣", "fishing pole", "fishing", "catch", "phishing"],
  ["🥊", "boxing glove", "boxing", "fight", "punch"],
  ["🛹", "skateboard", "skate"],
  ["⛸️", "ice skate", "skating", "ice"],
  ["🎿", "skis", "ski", "snow", "winter"],
  ["🏂", "snowboarder", "snowboard", "winter"],
  ["🏋️", "person lifting weights", "gym", "workout", "lift", "strong"],
  ["🚴", "person biking", "bike", "cycling", "bicycle"],
  ["🏆", "trophy", "win", "winner", "award", "champion", "first"],
  ["🥇", "1st place medal", "gold", "first", "win", "best"],
  ["🥈", "2nd place medal", "silver", "second"],
  ["🥉", "3rd place medal", "bronze", "third"],
  ["🏅", "sports medal", "medal", "award", "achievement"],
  ["🎖️", "military medal", "medal", "honor", "award"],
  ["🎯", "bullseye", "target", "goal", "aim", "accurate", "precision", "dart"],
  ["🎲", "game die", "dice", "random", "chance", "luck"],
  ["🎰", "slot machine", "gamble", "jackpot", "random"],
  ["🧩", "puzzle piece", "puzzle", "piece", "plugin", "extension", "fit", "integration"],
  ["🎮", "video game", "game", "gaming", "controller", "play"],
  ["🕹️", "joystick", "game", "arcade", "control"],
  ["🎨", "artist palette", "art", "design", "paint", "color", "creative", "theme", "ui"],
  ["🎭", "performing arts", "theater", "drama", "masks", "acting"],
  ["🎬", "clapper board", "movie", "film", "action", "cut", "scene"],
  ["🎤", "microphone", "mic", "sing", "voice", "podcast", "audio", "speech"],
  ["🎧", "headphone", "audio", "music", "listen", "sound"],
  ["🎵", "musical note", "music", "note", "song", "audio"],
  ["🎶", "musical notes", "music", "song", "audio"],
  ["🎹", "musical keyboard", "piano", "keys", "music"],
  ["🎸", "guitar", "music", "rock"],
  ["🥁", "drum", "music", "beat", "rhythm"],
  ["🎺", "trumpet", "music", "brass", "announce"],
  ["📯", "postal horn", "announce", "horn", "broadcast"],
  ["🔔", "bell", "notification", "alert", "ring", "reminder", "subscribe"],
  ["🔕", "bell with slash", "mute", "silence", "notifications off", "dnd"],
  ["📢", "loudspeaker", "announce", "broadcast", "shout", "public"],
  ["📣", "megaphone", "announce", "shout", "cheer", "marketing"],

  // ---- Travel & places ----------------------------------------------------
  ["🚗", "automobile", "car", "drive", "vehicle"],
  ["🚕", "taxi", "cab", "car"],
  ["🚙", "sport utility vehicle", "suv", "car"],
  ["🚌", "bus", "transit", "public transport"],
  ["🚑", "ambulance", "emergency", "medical", "urgent"],
  ["🚒", "fire engine", "firetruck", "emergency", "incident"],
  ["🚓", "police car", "police", "emergency"],
  ["🚚", "delivery truck", "truck", "shipping", "delivery", "logistics"],
  ["🚜", "tractor", "farm", "agriculture"],
  ["🏎️", "racing car", "race", "fast", "speed", "f1", "performance"],
  ["🏍️", "motorcycle", "bike", "motorbike"],
  ["🚲", "bicycle", "bike", "cycle"],
  ["🛴", "kick scooter", "scooter"],
  ["🚄", "high speed train", "train", "bullet train", "fast", "rail"],
  ["🚂", "locomotive", "train", "steam", "rail"],
  ["🚇", "metro", "subway", "underground", "tube"],
  ["✈️", "airplane", "flight", "plane", "travel", "deploy", "ship"],
  ["🛫", "airplane departure", "takeoff", "departure", "launch"],
  ["🛬", "airplane arrival", "landing", "arrival"],
  ["🚁", "helicopter", "chopper", "aircraft"],
  ["🚀", "rocket", "launch", "ship", "deploy", "fast", "space", "release", "startup"],
  ["🛸", "flying saucer", "ufo", "alien", "space"],
  ["🛰️", "satellite", "space", "orbit", "signal", "telemetry"],
  ["⛵", "sailboat", "boat", "sail", "sea"],
  ["🚤", "speedboat", "boat", "fast"],
  ["🛳️", "passenger ship", "cruise", "ship", "boat"],
  ["🚢", "ship", "boat", "shipping", "deploy", "release", "cargo"],
  ["⚓", "anchor", "harbor", "ship", "stable", "kubernetes", "helm"],
  ["🚧", "construction", "roadblock", "wip", "work in progress", "barrier", "blocked"],
  ["🚦", "vertical traffic light", "traffic", "signal", "status", "stoplight"],
  ["🚥", "horizontal traffic light", "traffic", "signal", "status"],
  ["🗺️", "world map", "map", "atlas", "navigate", "roadmap"],
  ["🧭", "compass", "navigate", "direction", "orient", "explore", "guide"],
  ["🏔️", "snow capped mountain", "mountain", "peak", "summit", "climb"],
  ["⛰️", "mountain", "peak", "hill", "climb"],
  ["🌋", "volcano", "eruption", "lava", "hot"],
  ["🏕️", "camping", "camp", "tent", "outdoors"],
  ["🏖️", "beach with umbrella", "beach", "vacation", "holiday", "sand"],
  ["🏝️", "desert island", "island", "vacation", "isolated"],
  ["🏠", "house", "home", "index", "main"],
  ["🏡", "house with garden", "home", "house"],
  ["🏢", "office building", "office", "work", "company", "enterprise", "business"],
  ["🏦", "bank", "money", "finance"],
  ["🏥", "hospital", "medical", "health", "emergency"],
  ["🏫", "school", "education", "learn"],
  ["🏭", "factory", "industry", "manufacturing", "production", "build"],
  ["🏰", "castle", "fortress", "medieval"],
  ["🗼", "tokyo tower", "tower", "landmark"],
  ["🗽", "statue of liberty", "liberty", "new york", "landmark"],
  ["🌉", "bridge at night", "bridge", "connect", "night"],
  ["🌃", "night with stars", "night", "city", "dark"],
  ["🌆", "cityscape at dusk", "city", "sunset", "skyline"],
  ["🏙️", "cityscape", "city", "skyline", "urban"],
  ["🎪", "circus tent", "circus", "carnival", "chaos"],

  // ---- Objects & tech -----------------------------------------------------
  ["⌚", "watch", "time", "wrist", "clock"],
  ["📱", "mobile phone", "phone", "mobile", "smartphone", "ios", "android"],
  ["💻", "laptop", "computer", "macbook", "dev", "work", "code"],
  ["🖥️", "desktop computer", "computer", "monitor", "screen", "workstation"],
  ["🖨️", "printer", "print", "paper"],
  ["⌨️", "keyboard", "typing", "keys", "input", "shortcut"],
  ["🖱️", "computer mouse", "mouse", "click", "pointer"],
  ["💽", "computer disk", "minidisc", "storage"],
  ["💾", "floppy disk", "save", "disk", "storage", "backup"],
  ["💿", "optical disk", "cd", "disc", "storage"],
  ["📀", "dvd", "disc", "video"],
  ["🧮", "abacus", "calculate", "math", "count"],
  ["🎥", "movie camera", "film", "record", "video"],
  ["📷", "camera", "photo", "picture", "snapshot", "screenshot"],
  ["📸", "camera with flash", "photo", "screenshot", "flash"],
  ["📹", "video camera", "record", "video", "film"],
  ["📼", "videocassette", "vhs", "tape", "retro"],
  ["🔍", "magnifying glass tilted left", "search", "find", "zoom", "inspect", "look", "query"],
  ["🔎", "magnifying glass tilted right", "search", "find", "zoom", "inspect", "query"],
  ["🔬", "microscope", "science", "lab", "inspect", "research", "analyze"],
  ["🔭", "telescope", "observe", "space", "watch", "monitor", "far"],
  ["📡", "satellite antenna", "signal", "broadcast", "network", "radar", "telemetry"],
  ["💡", "light bulb", "idea", "insight", "tip", "hint", "bright", "invention"],
  ["🔦", "flashlight", "torch", "light", "search"],
  ["🕯️", "candle", "light", "flame", "calm"],
  ["🪔", "diya lamp", "lamp", "light"],
  ["🔋", "battery", "power", "charge", "energy"],
  ["🪫", "low battery", "battery", "drained", "low power"],
  ["🔌", "electric plug", "plug", "power", "connect", "integration", "socket"],
  ["📞", "telephone receiver", "phone", "call", "support"],
  ["☎️", "telephone", "phone", "call", "landline"],
  ["📟", "pager", "beeper", "oncall", "alert", "retro"],
  ["📠", "fax machine", "fax", "legacy", "retro"],
  ["📺", "television", "tv", "screen", "watch"],
  ["📻", "radio", "broadcast", "listen", "audio"],
  ["⏰", "alarm clock", "alarm", "wake", "time", "reminder", "deadline"],
  ["⏱️", "stopwatch", "timer", "time", "measure", "benchmark", "latency", "duration"],
  ["⏲️", "timer clock", "timer", "countdown", "time"],
  ["🕰️", "mantelpiece clock", "clock", "time", "vintage"],
  ["⌛", "hourglass done", "time", "wait", "expired", "timeout"],
  ["⏳", "hourglass not done", "loading", "wait", "pending", "time", "progress"],
  ["📅", "calendar", "date", "schedule", "day", "plan", "event"],
  ["📆", "tear off calendar", "calendar", "date", "schedule"],
  ["🗓️", "spiral calendar", "calendar", "planner", "schedule"],
  ["📇", "card index", "contacts", "rolodex", "index"],
  ["📈", "chart increasing", "growth", "up", "trend", "metrics", "analytics", "improve"],
  ["📉", "chart decreasing", "down", "decline", "loss", "regression", "drop"],
  ["📊", "bar chart", "chart", "metrics", "stats", "analytics", "data", "report"],
  ["📋", "clipboard", "copy", "paste", "list", "tasks", "checklist"],
  ["📌", "pushpin", "pin", "pinned", "mark", "important", "sticky"],
  ["📍", "round pushpin", "location", "pin", "place", "here", "marker"],
  ["📎", "paperclip", "attach", "attachment", "clip", "file"],
  ["🖇️", "linked paperclips", "link", "attach", "chain"],
  ["📏", "straight ruler", "measure", "ruler", "size", "align"],
  ["📐", "triangular ruler", "measure", "geometry", "design", "angle"],
  ["✂️", "scissors", "cut", "trim", "snip", "clip"],
  ["🗃️", "card file box", "archive", "files", "storage", "database"],
  ["🗄️", "file cabinet", "archive", "storage", "files", "records"],
  ["🗑️", "wastebasket", "trash", "delete", "bin", "remove", "discard"],
  ["🔒", "locked", "lock", "secure", "private", "security", "closed", "protected"],
  ["🔓", "unlocked", "unlock", "open", "public", "insecure"],
  ["🔏", "locked with pen", "signed", "secure", "sign", "privacy"],
  ["🔐", "locked with key", "secure", "encrypted", "key", "auth", "security"],
  ["🔑", "key", "password", "auth", "secret", "access", "credential", "token"],
  ["🗝️", "old key", "key", "legacy", "access", "unlock"],
  ["🔨", "hammer", "build", "fix", "tool", "construct"],
  ["🪓", "axe", "chop", "cut", "tool"],
  ["⛏️", "pick", "mine", "dig", "tool"],
  ["⚒️", "hammer and pick", "tools", "build", "work"],
  ["🛠️", "hammer and wrench", "tools", "build", "fix", "maintenance", "settings", "config"],
  ["🗡️", "dagger", "blade", "sword", "attack"],
  ["⚔️", "crossed swords", "battle", "fight", "conflict", "versus", "war"],
  ["🔫", "water pistol", "gun", "pistol", "squirt"],
  ["🏹", "bow", "arrow", "aim"],
  ["🛡️", "shield", "defense", "protect", "security", "guard", "safe"],
  ["🔧", "wrench", "fix", "tool", "config", "settings", "repair", "adjust", "maintenance"],
  ["🪛", "screwdriver", "tool", "fix", "adjust"],
  ["🔩", "nut and bolt", "hardware", "screw", "bolt", "internals", "low level"],
  ["⚙️", "gear", "settings", "config", "cog", "engine", "machinery", "preferences", "options"],
  ["🧰", "toolbox", "tools", "kit", "utilities", "maintenance"],
  ["🧲", "magnet", "attract", "magnetic", "pull"],
  ["⚗️", "alembic", "chemistry", "experiment", "distill", "alchemy"],
  ["🧪", "test tube", "test", "experiment", "lab", "science", "testing", "qa"],
  ["🧫", "petri dish", "culture", "lab", "biology", "experiment"],
  ["🧬", "dna", "genetics", "biology", "genome", "clone"],
  ["🦠", "microbe", "virus", "germ", "bacteria", "infection"],
  ["💊", "pill", "medicine", "drug", "fix", "remedy"],
  ["💉", "syringe", "injection", "vaccine", "inject", "shot"],
  ["🩺", "stethoscope", "doctor", "health", "diagnose", "checkup", "healthcheck", "monitor"],
  ["🩹", "adhesive bandage", "bandaid", "patch", "fix", "hotfix", "quick fix", "temporary"],
  ["🚪", "door", "entrance", "exit", "gateway", "access"],
  ["🪟", "window", "view", "pane"],
  ["🛏️", "bed", "sleep", "rest", "hotel"],
  ["🚿", "shower", "wash", "clean", "bath"],
  ["🛁", "bathtub", "bath", "clean", "soak"],
  ["🧹", "broom", "clean", "cleanup", "sweep", "tidy", "housekeeping", "chore"],
  ["🧼", "soap", "clean", "wash", "sanitize"],
  ["🧽", "sponge", "clean", "wipe", "absorb"],
  ["🧴", "lotion bottle", "lotion", "squeeze", "bottle"],
  ["🪣", "bucket", "pail", "container", "storage"],
  ["🧺", "basket", "laundry", "container"],
  ["🛒", "shopping cart", "cart", "buy", "checkout", "ecommerce", "shop"],
  ["🛍️", "shopping bags", "shopping", "buy", "retail"],
  ["💳", "credit card", "payment", "pay", "billing", "card", "checkout"],
  ["💰", "money bag", "money", "cash", "budget", "cost", "funding", "revenue"],
  ["💵", "dollar banknote", "money", "cash", "dollar", "price"],
  ["💸", "money with wings", "spend", "expensive", "cost", "burn rate", "loss"],
  ["🪙", "coin", "money", "token", "crypto", "currency"],
  ["💎", "gem stone", "diamond", "gem", "premium", "valuable", "precious"],
  ["⚖️", "balance scale", "justice", "balance", "compare", "legal", "tradeoff", "fair"],
  ["🧾", "receipt", "invoice", "bill", "expense", "record"],
  ["✉️", "envelope", "email", "mail", "message", "letter"],
  ["📧", "e mail", "email", "mail", "message", "inbox"],
  ["📨", "incoming envelope", "email", "receive", "inbox", "message"],
  ["📩", "envelope with arrow", "send", "email", "outgoing", "submit"],
  ["📤", "outbox tray", "send", "outbox", "upload", "export"],
  ["📥", "inbox tray", "receive", "inbox", "download", "import"],
  ["📦", "package", "box", "parcel", "shipping", "bundle", "module", "library", "dependency"],
  ["📫", "closed mailbox with raised flag", "mailbox", "mail", "post"],
  ["📮", "postbox", "mail", "post", "send"],
  ["📜", "scroll", "document", "license", "history", "log", "ancient"],
  ["📄", "page facing up", "document", "file", "page", "text", "doc"],
  ["📃", "page with curl", "document", "page", "file"],
  ["📑", "bookmark tabs", "bookmark", "tabs", "index", "sections"],
  ["📰", "newspaper", "news", "article", "press", "changelog"],
  ["🗞️", "rolled up newspaper", "news", "press", "article"],
  ["📓", "notebook", "notes", "journal", "notebook"],
  ["📔", "notebook with decorative cover", "notebook", "journal", "diary"],
  ["📒", "ledger", "accounts", "notebook", "records"],
  ["📕", "closed book", "book", "read", "manual"],
  ["📗", "green book", "book", "read", "guide"],
  ["📘", "blue book", "book", "read", "reference"],
  ["📙", "orange book", "book", "read", "handbook"],
  ["📚", "books", "library", "docs", "documentation", "reading", "reference", "knowledge"],
  ["📖", "open book", "read", "docs", "documentation", "manual", "guide", "story"],
  ["🔖", "bookmark", "save", "mark", "tag", "label"],
  ["🏷️", "label", "tag", "name", "category", "release tag"],
  ["📝", "memo", "note", "write", "edit", "changelog", "draft", "notes", "pencil"],
  ["✏️", "pencil", "write", "edit", "draft", "sketch"],
  ["🖊️", "pen", "write", "sign", "ink"],
  ["🖋️", "fountain pen", "write", "sign", "ink", "author"],
  ["🖌️", "paintbrush", "paint", "design", "brush", "style"],
  ["🖍️", "crayon", "draw", "color", "sketch"],
  ["🗒️", "spiral notepad", "notes", "notepad", "todo", "list"],
  ["🗂️", "card index dividers", "folder", "organize", "sort", "categories", "files", "tabs"],
  ["📁", "file folder", "folder", "directory", "files", "organize"],
  ["📂", "open file folder", "folder", "open", "directory", "browse"],
  ["🔗", "link", "url", "chain", "hyperlink", "connect", "reference"],
  ["⛓️", "chains", "chain", "linked", "blockchain", "coupled"],
  ["🧱", "brick", "wall", "build", "foundation", "block", "component"],
  ["🏗️", "building construction", "build", "construction", "wip", "crane", "scaffolding"],
  ["🪜", "ladder", "climb", "steps", "escalate"],
  ["🔭", "telescope", "observe", "monitor", "vision"],
  ["🪄", "magic wand", "magic", "wizard", "auto", "generate", "transform", "spell"],
  ["🧿", "nazar amulet", "charm", "protection", "evil eye"],
  ["🎁", "wrapped gift", "gift", "present", "reward", "bonus", "feature"],
  ["🎈", "balloon", "party", "celebrate", "birthday", "lightweight"],
  ["🎉", "party popper", "celebrate", "party", "hooray", "launch", "success", "congrats"],
  ["🎊", "confetti ball", "celebrate", "party", "confetti"],
  ["🎀", "ribbon", "bow", "gift", "decorate"],
  ["🧵", "thread", "sewing", "thread", "concurrency", "string"],
  ["🪡", "sewing needle", "needle", "stitch", "sew", "patch"],
  ["🧶", "yarn", "wool", "knit", "tangle"],
  ["🔮", "crystal ball", "predict", "future", "magic", "fortune", "forecast"],
  ["🛎️", "bellhop bell", "service", "ring", "hotel", "attention"],
  ["🧳", "luggage", "travel", "suitcase", "baggage", "migration"],
  ["🏳️", "white flag", "surrender", "flag", "give up"],
  ["🏴", "black flag", "flag", "pirate"],
  ["🏁", "chequered flag", "finish", "race", "done", "complete", "goal"],
  ["🚩", "triangular flag", "flag", "red flag", "warning", "milestone", "mark"],

  // ---- Symbols ------------------------------------------------------------
  ["❤️", "red heart", "love", "heart", "like", "favorite"],
  ["🧡", "orange heart", "heart", "love"],
  ["💛", "yellow heart", "heart", "love"],
  ["💚", "green heart", "heart", "love"],
  ["💙", "blue heart", "heart", "love"],
  ["💜", "purple heart", "heart", "love"],
  ["🖤", "black heart", "heart", "dark"],
  ["🤍", "white heart", "heart", "pure"],
  ["🤎", "brown heart", "heart"],
  ["💔", "broken heart", "heartbreak", "sad", "break"],
  ["💕", "two hearts", "love", "hearts"],
  ["💖", "sparkling heart", "love", "sparkle", "heart"],
  ["💯", "hundred points", "100", "perfect", "score", "full marks", "agreed"],
  ["✅", "check mark button", "check", "done", "yes", "pass", "success", "complete", "tick", "ok"],
  ["☑️", "check box with check", "checkbox", "checked", "done", "todo", "task", "tick"],
  ["✔️", "check mark", "check", "tick", "done", "yes", "confirm"],
  ["❌", "cross mark", "no", "fail", "error", "wrong", "delete", "cancel", "x"],
  ["❎", "cross mark button", "no", "cancel", "reject"],
  ["⭕", "hollow red circle", "circle", "correct", "o"],
  ["⛔", "no entry", "stop", "forbidden", "blocked", "denied", "banned"],
  ["🚫", "prohibited", "no", "forbidden", "ban", "denied", "not allowed"],
  ["⚠️", "warning", "caution", "alert", "danger", "attention", "careful"],
  ["🚸", "children crossing", "caution", "crossing"],
  ["☢️", "radioactive", "nuclear", "radiation", "danger", "toxic"],
  ["☣️", "biohazard", "hazard", "danger", "toxic", "contamination"],
  ["❓", "question mark", "question", "help", "unknown", "ask", "why"],
  ["❔", "white question mark", "question", "help", "unsure"],
  ["❗", "exclamation mark", "important", "alert", "attention", "urgent", "warning"],
  ["❕", "white exclamation mark", "notice", "attention"],
  ["‼️", "double exclamation mark", "urgent", "important", "alert"],
  ["⁉️", "exclamation question mark", "surprise", "confused", "what"],
  ["💤", "zzz", "sleep", "idle", "inactive", "snooze", "dormant"],
  ["💢", "anger symbol", "angry", "mad", "frustrated"],
  ["💬", "speech balloon", "comment", "chat", "message", "talk", "discussion", "feedback", "say"],
  ["🗨️", "left speech bubble", "speech", "comment", "quote"],
  ["🗯️", "right anger bubble", "shout", "rant", "angry"],
  ["💭", "thought balloon", "think", "idea", "thought", "consider"],
  ["♻️", "recycling symbol", "recycle", "reuse", "refactor", "cycle", "loop", "sustainable"],
  ["✨", "sparkles", "new", "magic", "shine", "feature", "clean", "polish", "enhancement", "ai"],
  ["🌠", "shooting star", "wish", "star", "meteor"],
  ["🔆", "bright button", "brightness", "light", "increase"],
  ["🔅", "dim button", "brightness", "dim", "decrease"],
  ["🔴", "red circle", "red", "record", "stop", "critical", "dot"],
  ["🟠", "orange circle", "orange", "warning", "dot"],
  ["🟡", "yellow circle", "yellow", "caution", "dot"],
  ["🟢", "green circle", "green", "go", "healthy", "online", "pass", "dot"],
  ["🔵", "blue circle", "blue", "info", "dot"],
  ["🟣", "purple circle", "purple", "dot"],
  ["⚫", "black circle", "black", "off", "dot"],
  ["⚪", "white circle", "white", "empty", "dot"],
  ["🟥", "red square", "red", "square", "block"],
  ["🟩", "green square", "green", "square", "pass"],
  ["🟦", "blue square", "blue", "square"],
  ["🔶", "large orange diamond", "diamond", "orange"],
  ["🔷", "large blue diamond", "diamond", "blue"],
  ["🔺", "red triangle pointed up", "up", "increase", "triangle", "alert"],
  ["🔻", "red triangle pointed down", "down", "decrease", "triangle"],
  ["⬆️", "up arrow", "up", "increase", "north", "upgrade"],
  ["⬇️", "down arrow", "down", "decrease", "south", "downgrade"],
  ["⬅️", "left arrow", "left", "back", "previous", "west"],
  ["➡️", "right arrow", "right", "forward", "next", "east"],
  ["↩️", "right arrow curving left", "return", "back", "undo", "revert", "enter"],
  ["↪️", "left arrow curving right", "forward", "redo", "next"],
  ["🔀", "shuffle tracks button", "shuffle", "random", "swap", "mix"],
  ["🔁", "repeat button", "loop", "repeat", "retry", "again", "cycle"],
  ["🔂", "repeat single button", "repeat one", "loop"],
  ["🔃", "clockwise vertical arrows", "refresh", "reload", "sync", "rotate"],
  ["🔄", "counterclockwise arrows button", "refresh", "sync", "reload", "update", "rotate", "retry"],
  ["▶️", "play button", "play", "start", "run", "go", "resume"],
  ["⏸️", "pause button", "pause", "hold", "suspend", "wait"],
  ["⏹️", "stop button", "stop", "halt", "end"],
  ["⏺️", "record button", "record", "capture"],
  ["⏭️", "next track button", "next", "skip", "forward"],
  ["⏮️", "last track button", "previous", "back", "rewind"],
  ["⏩", "fast forward", "fast", "forward", "speed", "skip"],
  ["⏪", "fast reverse", "rewind", "back", "reverse"],
  ["🔼", "upwards button", "up", "increase", "collapse"],
  ["🔽", "downwards button", "down", "decrease", "expand"],
  ["➕", "plus", "add", "new", "create", "increase", "more"],
  ["➖", "minus", "remove", "subtract", "decrease", "less"],
  ["➗", "divide", "division", "split", "math"],
  ["✖️", "multiply", "times", "multiplication", "math", "close"],
  ["🟰", "heavy equals sign", "equals", "equal", "same", "math"],
  ["♾️", "infinity", "endless", "forever", "unlimited", "loop"],
  ["#️⃣", "keycap hash", "hash", "number", "channel", "tag"],
  ["*️⃣", "keycap asterisk", "asterisk", "star", "wildcard"],
  ["1️⃣", "keycap 1", "one", "first", "1", "step one"],
  ["2️⃣", "keycap 2", "two", "second", "2", "step two"],
  ["3️⃣", "keycap 3", "three", "third", "3", "step three"],
  ["🆕", "new button", "new", "fresh", "latest"],
  ["🆙", "up button", "up", "level up", "upgrade", "improve"],
  ["🆗", "ok button", "ok", "okay", "fine", "approved"],
  ["🆒", "cool button", "cool", "nice"],
  ["🆓", "free button", "free", "no cost", "open"],
  ["🈵", "no vacancy", "full", "no space", "capacity"],
  ["🔠", "input latin uppercase", "abc", "letters", "uppercase", "text"],
  ["🔤", "input latin letters", "abc", "letters", "alphabet", "text", "i18n"],
  ["🔣", "input symbols", "symbols", "special characters"],
  ["💲", "heavy dollar sign", "dollar", "money", "cost", "price"],
  ["©️", "copyright", "legal", "license", "rights"],
  ["®️", "registered", "trademark", "legal", "brand"],
  ["™️", "trade mark", "trademark", "brand", "legal"],
  ["〰️", "wavy dash", "wave", "dash", "squiggle"],
  ["🔞", "no one under eighteen", "adult", "restricted", "age"],
  ["📵", "no mobile phones", "no phones", "silence"],
  ["🔇", "muted speaker", "mute", "silent", "no sound"],
  ["🔈", "speaker low volume", "volume", "sound", "quiet"],
  ["🔉", "speaker medium volume", "volume", "sound"],
  ["🔊", "speaker high volume", "volume", "loud", "sound", "audio"],
  ["🎼", "musical score", "music", "score", "sheet"],
  ["♠️", "spade suit", "cards", "spade", "poker"],
  ["♥️", "heart suit", "cards", "hearts", "poker"],
  ["♦️", "diamond suit", "cards", "diamonds", "poker"],
  ["♣️", "club suit", "cards", "clubs", "poker"],
  ["🃏", "joker", "cards", "wildcard", "joker"],
  ["🀄", "mahjong red dragon", "mahjong", "game", "tile"],
  ["🎴", "flower playing cards", "cards", "hanafuda", "game"],
]

/** Deduped by char: a repeated entry in the table above must not double a row. */
export const EMOJIS: EmojiEntry[] = (() => {
  const seen = new Set<string>()
  const out: EmojiEntry[] = []
  for (const [char, name, ...keywords] of RAW) {
    if (seen.has(char)) continue
    seen.add(char)
    out.push({ char, name, keywords })
  }
  return out
})()

const BY_CHAR = new Map(EMOJIS.map((entry) => [entry.char, entry]))

/**
 * The curated grid the picker has always shown, as full entries. Anything in
 * EMOJI_CHOICES that is not in the dataset still appears — it just carries no
 * searchable name, which is better than silently dropping it from the grid.
 */
export const DEFAULT_EMOJIS: EmojiEntry[] = EMOJI_CHOICES.map(
  (char) => BY_CHAR.get(char) ?? { char, name: char, keywords: [] },
)

/** Curated grid members win ties: they are the ones the picker already blessed. */
const CURATED = new Set(EMOJI_CHOICES)

/**
 * Match strength, lower is better. An EXACT hit has to outrank a prefix one,
 * or "fire" lands on the fox (keyword "firefox") and "check" lands on the
 * clipboard (keyword "checklist") instead of the obvious emoji.
 */
function matchScore(entry: EmojiEntry, query: string): number {
  if (entry.name === query) return 0
  if (entry.keywords.some((keyword) => keyword === query)) return 1
  if (entry.name.startsWith(query)) return 2
  // A word inside the name counts too: "check mark" is a prefix hit for "mark".
  if (entry.name.split(" ").some((word) => word.startsWith(query))) return 3
  if (entry.keywords.some((keyword) => keyword.startsWith(query))) return 3
  if (entry.name.includes(query)) return 4
  if (entry.keywords.some((keyword) => keyword.includes(query))) return 4
  return -1
}

/**
 * Emojis matching `query`, best first.
 *
 * An empty query is the picker's resting state and returns the curated grid
 * untouched. Otherwise results are ordered by match strength (exact, then
 * prefix, then substring), with curated grid members and then shorter names
 * winning ties, and the table's own order as the final tiebreak so results
 * never reshuffle between keystrokes.
 */
export function searchEmoji(query: string, limit = 48): EmojiEntry[] {
  const q = query.trim().toLowerCase()
  // The resting view is the curated grid, whole: `limit` caps SEARCH results,
  // and letting it trim the grid would quietly drop icons the picker has
  // always offered.
  if (!q) return [...DEFAULT_EMOJIS]
  if (limit <= 0) return []

  const scored: { entry: EmojiEntry; score: number; index: number }[] = []
  for (const [index, entry] of EMOJIS.entries()) {
    const score = matchScore(entry, q)
    if (score >= 0) scored.push({ entry, score, index })
  }

  scored.sort((a, b) => {
    if (a.score !== b.score) return a.score - b.score
    const aCurated = CURATED.has(a.entry.char) ? 0 : 1
    const bCurated = CURATED.has(b.entry.char) ? 0 : 1
    if (aCurated !== bCurated) return aCurated - bCurated
    if (a.entry.name.length !== b.entry.name.length) {
      return a.entry.name.length - b.entry.name.length
    }
    return a.index - b.index
  })

  return scored.slice(0, limit).map((hit) => hit.entry)
}
