import { AtSign, LoaderCircle, RefreshCw, Trash2 } from "lucide-react"
import { useState, type FormEvent } from "react"
import { cn } from "~/lib/cn"
import { NO_DRAG_REGION } from "~/lib/dragRegion"
import { relativeTime } from "~/lib/format"
import { openExternal } from "~/lib/openExternal"
import { zooAddXWatch, zooRemoveXWatch, zooSetXWatchSchedule, type ZooArea, type ZooXWatch } from "~/lib/zoo"
import { areaName, type AreaSelection } from "~/lib/zooAreas"
import { checkXAndExtract, extractPendingXWatch, normalizeXHandleInput, summarizeXCheck, xWatchNeedsExtraction, xWatchStatusLabel, type XWatchRunPhase } from "~/lib/zooXWatch"
import { AreaAssignMenu, AreaBadge } from "./AreaSwitcher"
import { Select } from "../settings/common"
import { Button } from "../ui/button"
import { Input } from "../ui/input"
import { Notice } from "./parts"

const INTERVALS = [30, 60, 90, 120, 180]
const PHASE: Record<XWatchRunPhase, string> = { checking: "Checking X with Grok", exporting: "Bundling posts", starting: "Starting extraction", thinking: "Reading posts", recording: "Recording signals" }

export function XWatchList({ watches, areas, intervalMinutes, lastSuccessAt, areaId, baseUrl, onRefresh, onAssignArea }: { watches: ZooXWatch[]; areas: ZooArea[]; intervalMinutes: number; lastSuccessAt: number | null; areaId: AreaSelection; baseUrl?: string | null; onRefresh(): Promise<void>; onAssignArea(sourceId: string, areaId: string | null): void }) {
  const [handle, setHandle] = useState(""); const [busy, setBusy] = useState<string | null>(null); const [phase, setPhase] = useState<XWatchRunPhase | null>(null); const [error, setError] = useState<string | null>(null); const [note, setNote] = useState<string | null>(null)
  const add = async (event: FormEvent) => { event.preventDefault(); const value = normalizeXHandleInput(handle); if (!value || busy) return; setBusy("add"); setError(null); const result = await zooAddXWatch(value, areaId); setBusy(null); if (!result.ok) setError(result.error); else { setHandle(""); setNote(`Watching ${result.watch.label}.`); await onRefresh() } }
  const remove = async (watch: ZooXWatch) => { if (busy) return; setBusy(watch.id); setError(null); const result = await zooRemoveXWatch(watch.id); setBusy(null); if (!result.ok) setError(result.error); else setNote(`Stopped watching ${watch.label}. Existing evidence stays on the board.`); await onRefresh() }
  const check = async (watch: ZooXWatch | null) => { if (busy) return; setBusy(watch?.id ?? "all"); setError(null); setNote(null); const result = await checkXAndExtract(watch, { baseUrl, onPhase: setPhase }); setPhase(null); setBusy(null); if (result.error) setError(result.error); setNote(result.insightCount === null ? summarizeXCheck(result.results) : `${summarizeXCheck(result.results)} · ${result.insightCount} signal${result.insightCount === 1 ? "" : "s"} recorded`); await onRefresh() }
  const extract = async (watch: ZooXWatch) => { if (busy) return; setBusy(watch.id); setError(null); const result = await extractPendingXWatch(watch, { baseUrl, onPhase: setPhase }); setPhase(null); setBusy(null); if (result.error) setError(result.error); else setNote(`${result.insightCount ?? 0} signal${result.insightCount === 1 ? "" : "s"} recorded from ${watch.label}.`); await onRefresh() }
  const schedule = async (value: number) => { setError(null); const result = await zooSetXWatchSchedule(value); if (!result.ok) setError(result.error); await onRefresh() }
  return <section className={cn(NO_DRAG_REGION, "flex min-w-0 flex-col gap-2 rounded-xl border border-border/70 bg-card/60 p-3")}>
    <div className="flex min-w-0 flex-wrap items-center gap-2"><AtSign className="size-4 shrink-0 text-primary"/><p className="min-w-0 flex-1 font-medium text-[13px]">X Watch</p><label className="flex shrink-0 items-center gap-1.5 text-[11.5px] text-muted-foreground">Every <Select value={String(intervalMinutes)} onChange={(value) => void schedule(Number(value))} className="h-7 w-[6rem] text-[11.5px]">{INTERVALS.map((value) => <option key={value} value={value}>{value} min</option>)}</Select></label><Button size="sm" variant="outline" disabled={busy !== null || !watches.length} onClick={() => void check(null)}>{busy === "all" ? <LoaderCircle className="animate-spin"/> : <RefreshCw/>}Check all</Button></div>
    <p className="text-[11.5px] text-muted-foreground">Original posts collected by a repository-less, session-pinned Grok run and turned into Inbox signals.{lastSuccessAt ? ` Last successful pass ${relativeTime(lastSuccessAt)}.` : " Not successfully checked yet."}</p>
    {!!watches.length && <ul className="flex min-w-0 flex-col gap-1.5">{watches.map((watch) => { const pending = xWatchNeedsExtraction(watch); const area = areaName(areas, watch.areaId); return <li key={watch.id} className="flex min-w-0 flex-col gap-1 rounded-lg border border-border/60 bg-muted/20 px-2.5 py-2"><div className="flex min-w-0 flex-wrap items-center gap-2"><AtSign className="size-3.5 shrink-0 text-muted-foreground"/><button type="button" className="min-w-0 flex-1 cursor-pointer truncate text-left font-mono text-[12px] hover:underline" onClick={() => openExternal(`https://x.com/${watch.handle}`)}>{watch.label}</button>{area && <AreaBadge name={area}/>}<AreaAssignMenu areas={areas} areaId={watch.areaId} disabled={busy !== null} onAssign={(next) => onAssignArea(watch.sourceId, next)}/><Button size="sm" variant="outline" disabled={busy !== null} onClick={() => void check(watch)}>{busy === watch.id ? <LoaderCircle className="animate-spin"/> : <RefreshCw/>}Check now</Button><Button size="sm" variant="ghost" aria-label={`Stop watching ${watch.label}`} disabled={busy !== null} onClick={() => void remove(watch)}><Trash2/></Button></div><div className="flex min-w-0 flex-wrap items-center gap-2"><span className={cn("min-w-0 break-words text-[11.5px]", watch.lastStatus === "error" ? "text-destructive" : "text-muted-foreground")}>{busy === watch.id && phase ? PHASE[phase] : xWatchStatusLabel(watch)}</span>{pending && busy !== watch.id && <Button size="sm" variant="ghost" disabled={busy !== null} onClick={() => void extract(watch)}>Extract new posts</Button>}</div></li> })}</ul>}
    <form onSubmit={add} className="flex min-w-0 flex-wrap items-center gap-1.5"><Input value={handle} onChange={(event) => setHandle(event.target.value)} placeholder="@handle — e.g. @theo" spellCheck={false} autoComplete="off" aria-label="X account to watch" className="min-w-40 flex-1"/><Button type="submit" size="sm" disabled={busy !== null || !normalizeXHandleInput(handle)}>{busy === "add" ? <LoaderCircle className="animate-spin"/> : null}Watch</Button></form>
    {error && <Notice text={error}/>} {note && !error && <Notice text={note} tone="muted"/>}
  </section>
}
